### ISSUE TITLE
Devices do not support Rgba8UnormSrgb

### ISSUE THREAD

**Issue by Diegovsky** [Gui-Yom/nuance#1]
Hey there! I saw your post on reddit and came here to see this beauty in action. However, it seems none of my devices (laptop with igpu and dgpu) support Rgba8UnormSrgb:
[intel.log](https://github.com/Gui-Yom/nuance/files/7087505/intel.log)
[nvidia.log](https://github.com/Gui-Yom/nuance/files/7087506/nvidia.log)

I used the 3.1  release's `nuance` linux executable as I can't build the project due to nightly ICEs. All my drivers are up-to-date.

After a quick search, [it seems that BGR is widely used in many graphics APIs](https://stackoverflow.com/questions/367449/what-exactly-is-bgr-color-space) which explains why on my linux machine, Vulkan only supports BGR and not RGB like Window's DX12 .

I'm just getting started in the world of graphics APIs and I don't know how this can be solved/implemented. What do you think?

Edit: grammar.

**Comment by rezural** [comment]
as a workaround, compiling from source and changing the offending line works:

```rust
let format = TextureFormat::Bgra8UnormSrgb;
```

**Comment by Gui-Yom** [comment]
Yeah, I do not recall why I used Rgba8UnormSrgb in the first place, but I left it there without switching back to Bgra.
I had no problem with it since I only test with my integrated intel gpu that supports it.

I will push a new version to fix this.

**Comment by Diegovsky** [comment]
Thanks a lot :)
